<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'=>'kadnum-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        array('name'=>'post_id',
            'htmlOptions' => array('width' => '10px'),
        ),
        array('name'=>'kad0',
            'htmlOptions' => array('width' => '25px'),
        ),
        array('name'=>'kad1',
            'htmlOptions' => array('width' => '10px'),
        ),
        array('name'=>'kad2',
            'htmlOptions' => array('width' => '10px'),
        ),
        array('name'=>'kad3',
            'htmlOptions' => array('width' => '20px'),
        ),

        array('name' => 'date',
            "type" => "raw",
            'value'=> 'date("Y-m-d H:i:s",$data->date)',
            'htmlOptions' => array('width' => '120px'),
        ),
        'title',
        'fio',
        array('class'=>'CButtonColumn',
            'template'=>'{view}{update}',
            'viewButtonUrl' => 'Yii::app()->createUrl("site/index", array("id"=>$data->post_id))',
            'updateButtonUrl' => 'Yii::app()->createUrl("site/upxml", array("id"=>$data->id))',
            ),
    ),
)); ?>